package net.autotask.atws.v1_5;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-07T12:44:05.987-05:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://autotask.net/ATWS/v1_5/", name = "ATWSSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ATWSSoap {

    /**
     * Default EntityInfo function, returns entity info for version 1.5
     */
    @WebMethod(action = "http://autotask.net/ATWS/v1_5/GetEntityInfo")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetEntityInfoResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", partName = "parameters")
    public GetEntityInfoResponse getEntityInfo(
        @WebParam(partName = "parameters", name = "GetEntityInfo", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        GetEntityInfo parameters
    );

    /**
     * getThresholdAndUsageInfo function to get the threshold, timeframe and current number of external request.
     */
    @WebMethod(action = "http://autotask.net/ATWS/v1_5/getThresholdAndUsageInfo")
    @RequestWrapper(localName = "getThresholdAndUsageInfo", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetThresholdAndUsageInfo")
    @ResponseWrapper(localName = "getThresholdAndUsageInfoResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetThresholdAndUsageInfoResponse")
    @WebResult(name = "getThresholdAndUsageInfoResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public net.autotask.atws.v1_5.ATWSResponse getThresholdAndUsageInfo();

    /**
     * Create Attachment function for version 1.5
     */
    @WebMethod(operationName = "CreateAttachment", action = "http://autotask.net/ATWS/v1_5/CreateAttachment")
    @RequestWrapper(localName = "CreateAttachment", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.CreateAttachment")
    @ResponseWrapper(localName = "CreateAttachmentResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.CreateAttachmentResponse")
    @WebResult(name = "CreateAttachmentResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public long createAttachment(
        @WebParam(name = "attachment", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        net.autotask.atws.v1_5.Attachment attachment
    );

    /**
     * Gets information about what zone/URL the client should use.
     */
    @WebMethod(action = "http://autotask.net/ATWS/v1_5/getZoneInfo")
    @RequestWrapper(localName = "getZoneInfo", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetZoneInfo")
    @ResponseWrapper(localName = "getZoneInfoResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetZoneInfoResponse")
    @WebResult(name = "getZoneInfoResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public net.autotask.atws.v1_5.ATWSZoneInfo getZoneInfo(
        @WebParam(name = "UserName", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        java.lang.String userName
    );

    /**
     * create function will insert any new entities into the Autotask system.
     */
    @WebMethod(action = "http://autotask.net/ATWS/v1_5/create")
    @RequestWrapper(localName = "create", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.CreateResponse")
    @WebResult(name = "createResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public net.autotask.atws.v1_5.ATWSResponse create(
        @WebParam(name = "Entities", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        net.autotask.atws.v1_5.ArrayOfEntity entities
    );

    /**
     * Delete Attachment function for version 1.5
     */
    @WebMethod(operationName = "DeleteAttachment", action = "http://autotask.net/ATWS/v1_5/DeleteAttachment")
    @RequestWrapper(localName = "DeleteAttachment", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.DeleteAttachment")
    @ResponseWrapper(localName = "DeleteAttachmentResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.DeleteAttachmentResponse")
    @WebResult(name = "DeleteAttachmentResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public java.lang.String deleteAttachment(
        @WebParam(name = "attachmentId", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        long attachmentId
    );

    /**
     * Returns the requested markup format for a given invoice.
     */
    @WebMethod(operationName = "GetInvoiceMarkup", action = "http://autotask.net/ATWS/v1_5/GetInvoiceMarkup")
    @RequestWrapper(localName = "GetInvoiceMarkup", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetInvoiceMarkup")
    @ResponseWrapper(localName = "GetInvoiceMarkupResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetInvoiceMarkupResponse")
    @WebResult(name = "GetInvoiceMarkupResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public java.lang.String getInvoiceMarkup(
        @WebParam(name = "InvoiceId", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        int invoiceId,
        @WebParam(name = "Format", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        java.lang.String format
    );

    /**
     * Default GetUDFInfo function, returns information for version 1.5
     */
    @WebMethod(action = "http://autotask.net/ATWS/v1_5/getUDFInfo")
    @RequestWrapper(localName = "getUDFInfo", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetUDFInfo")
    @ResponseWrapper(localName = "getUDFInfoResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetUDFInfoResponse")
    @WebResult(name = "getUDFInfoResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public net.autotask.atws.v1_5.ArrayOfField getUDFInfo(
        @WebParam(name = "psTable", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        java.lang.String psTable
    );

    /**
     * query function to extract data, sXML is in QueryXML format.
     */
    @WebMethod(action = "http://autotask.net/ATWS/v1_5/query")
    @RequestWrapper(localName = "query", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.QueryResponse")
    @WebResult(name = "queryResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public net.autotask.atws.v1_5.ATWSResponse query(
        @WebParam(name = "sXML", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        java.lang.String sXML
    );

    /**
     * update function will update all entities with the new values passed to it.
     */
    @WebMethod(action = "http://autotask.net/ATWS/v1_5/update")
    @RequestWrapper(localName = "update", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.UpdateResponse")
    @WebResult(name = "updateResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public net.autotask.atws.v1_5.ATWSResponse update(
        @WebParam(name = "Entities", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        net.autotask.atws.v1_5.ArrayOfEntity entities
    );

    /**
     * delete function will delete all the entities passed to it.
     */
    @WebMethod(action = "http://autotask.net/ATWS/v1_5/delete")
    @RequestWrapper(localName = "delete", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.DeleteResponse")
    @WebResult(name = "deleteResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public net.autotask.atws.v1_5.ATWSResponse delete(
        @WebParam(name = "Entities", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        net.autotask.atws.v1_5.ArrayOfEntity entities
    );

    /**
     * Default GetFieldInfo function, returns information for version 1.5
     */
    @WebMethod(operationName = "GetFieldInfo", action = "http://autotask.net/ATWS/v1_5/GetFieldInfo")
    @RequestWrapper(localName = "GetFieldInfo", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetFieldInfo")
    @ResponseWrapper(localName = "GetFieldInfoResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetFieldInfoResponse")
    @WebResult(name = "GetFieldInfoResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public net.autotask.atws.v1_5.ArrayOfField getFieldInfo(
        @WebParam(name = "psObjectType", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        java.lang.String psObjectType
    );

    /**
     * GetWsdlVersion function to get the current wsdl version for the zone.
     */
    @WebMethod(operationName = "GetWsdlVersion", action = "http://autotask.net/ATWS/v1_5/GetWsdlVersion")
    @RequestWrapper(localName = "GetWsdlVersion", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetWsdlVersion")
    @ResponseWrapper(localName = "GetWsdlVersionResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetWsdlVersionResponse")
    @WebResult(name = "GetWsdlVersionResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public java.lang.String getWsdlVersion();

    /**
     * Get Attachment function, returns file attachment info for version 1.5
     */
    @WebMethod(operationName = "GetAttachment", action = "http://autotask.net/ATWS/v1_5/GetAttachment")
    @RequestWrapper(localName = "GetAttachment", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetAttachment")
    @ResponseWrapper(localName = "GetAttachmentResponse", targetNamespace = "http://autotask.net/ATWS/v1_5/", className = "net.autotask.atws.v1_5.GetAttachmentResponse")
    @WebResult(name = "GetAttachmentResult", targetNamespace = "http://autotask.net/ATWS/v1_5/")
    public net.autotask.atws.v1_5.Attachment getAttachment(
        @WebParam(name = "attachmentId", targetNamespace = "http://autotask.net/ATWS/v1_5/")
        long attachmentId
    );
}
